runtime: python
vm: true
entrypoint: gunicorn -b :$PORT main:app

runtime_config:
  python_version: 3

#[START env]
env_variables:
    # Replace user, password, database, project, and instance with the values obtained
    # when configuring your Cloud SQL instance.
    SQLALCHEMY_DATABASE_URI: >-
      mysql+pymysql://USER:PASSWORD@/DATABASE?unix_socket=/cloudsql/PROJECT:us-central1:INSTANCE
#[END env]

#[START cloudsql_settings]
# Replace project and instance with the values obtained  when configuring your
# Cloud SQL instance.
beta_settings:
    cloud_sql_instances: PROJECT:us-central1:INSTANCE
#[END cloudslq_settings]
