assign_issues:
  - busunkim96
  - leahecole
  - crwilcox
  - tmatsuo
  - engelke
  - kurtisvg
  - dinagraves

assign_prs:
  - busunkim96
  - leahecole
  - crwilcox
  - tmatsuo
  - engelke
  - kurtisvg
  - dinagraves
