sudo: false
#add language, etc. here
language: python

cache:
  directories:
        - $HOME/gcloud/
env:
        - PATH=$PATH:$HOME/gcloud/google-cloud-sdk/bin GOOGLE_APPLICATION_CREDENTIALS=$TRAVIS_BUILD_DIR/client_secrets.json PYTHONPATH=${HOME}/gcloud/platform/google_appengine #Other environment variables on same line

before_install:
        #ENCRYPT YOUR PRIVATE KEY (If you need authentication)
        # 1. Install and login to the Travis CLI:
        #       $ gem install travis
        #       $ travis login
        # 2. Move your json private key to client_secrets.json
        # 3. Run:
        #       $ travis encrypt-file client_secrets.json --add
        # 4. Commit changes:
        #       $ git add client_secrets.json.enc
        #       $ git commit client_secrets.json.enc .travis.yml

        - if [ ! -d $HOME/gcloud/google-cloud-sdk ]; then
                mkdir -p $HOME/gcloud &&
                wget https://dl.google.com/dl/cloudsdk/release/google-cloud-sdk.tar.gz --directory-prefix=$HOME/gcloud &&
                cd $HOME/gcloud &&
                tar xzf google-cloud-sdk.tar.gz &&
                printf '\ny\n\ny\ny\n' | ./google-cloud-sdk/install.sh &&
                cd $TRAVIS_BUILD_DIR;
          fi
        - printf 'y\n' | gcloud components update
        - openssl aes-256-cbc -K $encrypted_4fda24e244ca_key -iv $encrypted_4fda24e244ca_iv -in python-docs-samples.json.enc -out python-docs-samples.json -d
        - if [ -a python-docs-samples.json ]; then
                gcloud auth activate-service-account --key-file python-docs-samples.json;
          fi

install:
        - pip install tox

script:
        - tox
