sudo: false
#add language, etc. here
language: python

cache:
  directories:
  - $HOME/.cache

env:
  global:
  - PATH=${PATH}:${HOME}/gcloud/google-cloud-sdk/bin
  - GOOGLE_APPLICATION_CREDENTIALS=${TRAVIS_BUILD_DIR}/python-docs-samples.json
  - GAE_PYTHONPATH=${HOME}/.cache/google_appengine
  - TEST_BUCKET_NAME=bigquery-devrel-samples-bucket
  - TEST_PROJECT_ID=bigquery-devrel-samples

before_install:
- tests/scripts/travis-before-install.sh

install:
- pip install tox coveralls

script:
- tox

after_success:
- coveralls
