sudo: false
#add language, etc. here
language: python

branches:
  only:
    - master

cache:
  directories:
  - $HOME/.cache

env:
  global:
  - PATH=${PATH}:${HOME}/gcloud/google-cloud-sdk/bin
  - GOOGLE_APPLICATION_CREDENTIALS=${TRAVIS_BUILD_DIR}/python-docs-samples.json
  - GAE_PYTHONPATH=${HOME}/.cache/google_appengine
  - TEST_BUCKET_NAME=bigquery-devrel-samples-bucket
  - TEST_PROJECT_ID=bigquery-devrel-samples

before_install:
- tests/scripts/travis-before-install.sh

install:
# TODO: unpin tox when the following issue is fixed
# https://bitbucket.org/hpk42/tox/issues/285/tox-220-breaks-some-toxini-config-files
- pip install tox

script:
- tox

# Coveralls is disabled in travis because travis does not run all of our
# tests. The full suite of tests is run on an internal Jenkins instance.
# after_success:
# - coveralls
