sudo: false
language: python
services:
- memcached
- mysql
- redis-server
branches:
  only:
  - master
cache:
  directories:
  - $HOME/.cache
env:
  global:
  - PATH=${PATH}:${HOME}/gcloud/google-cloud-sdk/bin
  - GOOGLE_APPLICATION_CREDENTIALS=${TRAVIS_BUILD_DIR}/testing/resources/service-account.json
  - GOOGLE_CLIENT_SECRETS=${TRAVIS_BUILD_DIR}/testing/resources/client-secrets.json
  - GAE_ROOT=${HOME}/.cache/
  - secure: f3aU0nf8ZBV2QfZ03oeqvR0f/JM69P/7IH3IGoBcRUWVIXXhQ6Esh9SmCUILPtis1ZKu11I9c+NDebZio7PFgTqfvLbKzAkrg0ucx+Bsyx6379/S1trbLeKunERSGA3GqK6+OCoR5q/9sKxNvlm/c/e9h7xZmPfP5W0qwVR/K0M=
addons:
  apt:
    sources:
    - deadsnakes
    packages:
    - portaudio19-dev
    - python3.5
    - python3.5-dev
install:
- pip install --upgrade pip wheel virtualenv
- pip install nox-automation coverage
script:
- ./scripts/travis.sh
after_script:
- coverage report
