sudo: false
language: python
services:
- memcached
- mysql
branches:
  only:
  - master
cache:
  directories:
  - $HOME/.cache
env:
  global:
  - PATH=${PATH}:${HOME}/gcloud/google-cloud-sdk/bin
  - GOOGLE_APPLICATION_CREDENTIALS=${TRAVIS_BUILD_DIR}/testing/resources/service-account.json
  - GOOGLE_CLIENT_SECRETS=${TRAVIS_BUILD_DIR}/testing/resources/client-secrets.json
  - GAE_ROOT=${HOME}/.cache/
  - secure: TQ0e6XKeFwVkoqgOJH9f/afyRouUSC6s7LC32C4JS+O2X4sXyXTPXACmzu5wCW0BXPc6HvITMLvkf7g6XXyGlCPkjM8Uw5Vg5F9+cwN1HMlI+gK6bMGTUfrwN5ruFT+KmEnD4F93NY3xkDbZd0fw23d/mVloTc6V0gUsxEUkuhM=
addons:
  apt:
    packages:
    - portaudio19-dev
before_install:
- pip install --upgrade pip wheel virtualenv
- if [ $TRAVIS_SECURE_ENV_VARS == "true" ]; then
    openssl aes-256-cbc -k "$secrets_password" -in secrets.tar.enc -out secrets.tar -d;
    tar xvf secrets.tar;
  fi
install:
- pip install nox-automation coverage
script:
- if [ $TRAVIS_SECURE_ENV_VARS == "true" ] ; then
      source ${TRAVIS_BUILD_DIR}/testing/resources/test-env.sh;
      nox --stop-on-first-error -s lint travis;
    else
       # only run lint on external PRs
       nox --stop-on-first-error -s lint travis;
  fi

after_script:
- coverage report
