sudo: false
language: python
services:
- memcached
- mysql
- redis-server
branches:
  only:
  - master
cache:
  directories:
  - $HOME/.cache
env:
  global:
  - PATH=${PATH}:${HOME}/gcloud/google-cloud-sdk/bin
  - GOOGLE_APPLICATION_CREDENTIALS=${TRAVIS_BUILD_DIR}/testing/resources/service-account.json
  - GOOGLE_CLIENT_SECRETS=${TRAVIS_BUILD_DIR}/testing/resources/client-secrets.json
  - GAE_ROOT=${HOME}/.cache/
  - secure: TQ0e6XKeFwVkoqgOJH9f/afyRouUSC6s7LC32C4JS+O2X4sXyXTPXACmzu5wCW0BXPc6HvITMLvkf7g6XXyGlCPkjM8Uw5Vg5F9+cwN1HMlI+gK6bMGTUfrwN5ruFT+KmEnD4F93NY3xkDbZd0fw23d/mVloTc6V0gUsxEUkuhM=
addons:
  apt:
    sources:
    - deadsnakes
    packages:
    - portaudio19-dev
    - python3.5
    - python3.5-dev
install:
- pip install --upgrade pip wheel virtualenv
- pip install nox-automation coverage
script:
- ./scripts/travis.sh
after_script:
- coverage report
